ninja: fix hack to use system ninja
Fixes:

```
     Traceback (most recent call last):
      File "/tmp/pip-build-env-lqaahaw0/overlay/bin/ninja", line 5, in <module>
        from ninja import ninja
      File "/tmp/pip-build-env-lqaahaw0/overlay/lib/python3.9/site-packages/ninja/__init__.py", line 30, in <module>
        from skbuild.constants import CMAKE_INSTALL_DIR as SKBUILD_CMAKE_INSTALL_DIR

    ModuleNotFoundError: No module named 'skbuild'
```

by removing code to support running from the source tree. Because we
don't have a data/ directory, we were triggering this condition.