Improve RequirementType enum
The previous implementation of `RequirementType` enum was confusing and
had subtile bugs. It was surprising that one enum member was equal to
several other enum members. The `__ne__` implementation was wrong and
the presence of `__eq__` without a `__hash__` in the subclass broke
hashability.

```
>>> from fromager.requirements_file import RequirementType
>>> hash(RequirementType.BUILD)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'RequirementType'
>>> RequirementType.BUILD.__eq__(None)
NotImplemented
>>> RequirementType.BUILD.__ne__(None)
True
```

The `__ne__` method should have returned `NotImplemented` marker, too.

The new implementation removes `__eq__` and instead introduces
`is_build_requirement` and `is_install_requirement` flags.
`if req_type.is_build_requirement:` is easier to understand.

Signed-off-by: Christian Heimes <cheimes@redhat.com>